name: nullarbor
channels:
  - defaults
  - conda-forge
  - bioconda
  - r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=0_gnu
  - abricate=1.0.1=h1341992_0
  - alsa-lib=1.2.3=h516909a_0
  - any2fasta=0.4.2=2
  - aragorn=1.2.38=h516909a_3
  - barrnap=0.9=3
  - bcftools=1.10.2=h4f4756c_2
  - bedtools=2.29.2=hc088bd4_0
  - blast=2.9.0=pl526he19e7b1_7
  - boost=1.70.0=py37h9de70de_1
  - boost-cpp=1.70.0=h8e57a91_2
  - bowtie2=2.4.1=py37h4ef193e_2
  - brotlipy=0.7.0=py37h7b6447c_1000
  - bwa=0.7.17=hed695b0_7
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2020.6.24=0
  - cairo=1.16.0=hcf35c78_1003
  - cd-hit=4.8.1=h8b12597_3
  - certifi=2020.6.20=py37_0
  - cffi=1.14.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - circos=0.69.8=0
  - click=7.1.2=py_0
  - clustalw=2.1=hc9558a2_5
  - coloredlogs=10.0=py37_0
  - colormath=3.0.0=py_2
  - cryptography=2.9.2=py37h1ba5d50_0
  - curl=7.71.1=he644dc0_2
  - cycler=0.10.0=py_2
  - decorator=4.4.2=py_0
  - emboss=6.6.0=hf7d6862_3
  - entrez-direct=13.3=pl526h375a9b1_0
  - expat=2.2.9=he1b5a44_2
  - fastp=0.20.1=h8b12597_0
  - fasttree=2.1.10=h516909a_4
  - flash=1.2.11=hed695b0_5
  - fontconfig=2.13.1=h86ecdb6_1001
  - freebayes=1.3.2=py37h26878c9_2
  - freetype=2.10.2=he06d7ca_0
  - fribidi=1.0.10=h516909a_0
  - future=0.18.2=py37_1
  - gettext=0.19.8.1=hc5be6a0_1002
  - giflib=5.2.1=h516909a_2
  - glib=2.65.0=h6f030ca_0
  - glimmerhmm=3.0.4=pl526hf484d3e_3
  - graphite2=1.3.13=he1b5a44_1001
  - graphviz=2.42.3=h0511662_0
  - gsl=2.6=h294904e_0
  - harfbuzz=2.4.0=h9f30f68_3
  - hmmer=3.3=he1b5a44_1
  - htslib=1.10.2=hd3b49d5_1
  - humanfriendly=8.2=py37_0
  - icu=64.2=he1b5a44_1
  - idna=2.10=py_0
  - infernal=1.1.2=h516909a_3
  - jinja2=2.11.2=py_0
  - joblib=0.16.0=py_0
  - jpeg=9d=h516909a_0
  - k8=0.2.5=he513fc3_0
  - kiwisolver=1.2.0=py37h99015e2_0
  - kmc=3.1.2rc1=h2d02072_0
  - kraken2=2.0.9beta=pl526hc9558a2_0
  - krb5=1.17.1=hfafb76e_1
  - lcms2=2.11=hbd6801e_0
  - ld_impl_linux-64=2.34=h53a641e_7
  - libblas=3.8.0=17_openblas
  - libcblas=3.8.0=17_openblas
  - libcurl=7.71.1=hcdd3856_2
  - libdb=6.1.26=he1b5a44_2002
  - libdeflate=1.6=h516909a_0
  - libedit=3.1.20191231=h46ee950_1
  - libfaketime=0.9.8=h516909a_0
  - libffi=3.2.1=he1b5a44_1007
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgd=2.2.5=h307a58e_1007
  - libgfortran-ng=7.5.0=hdf63c60_6
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1006
  - libidn11=1.34=h1cef754_0
  - libidn2=2.3.0=h516909a_0
  - liblapack=3.8.0=17_openblas
  - libopenblas=0.3.10=pthreads_hb3c22a3_2
  - libpng=1.6.37=hed695b0_1
  - libssh2=1.9.0=hab1572f_4
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libtool=2.4.6=h14c3975_1002
  - libunistring=0.9.10=h14c3975_0
  - libuuid=2.32.1=h14c3975_1000
  - libwebp=1.0.2=h56121f0_5
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.10=hee79883_0
  - libxslt=1.1.33=h31b3aaa_0
  - lighter=1.1.2=he513fc3_2
  - llvm-openmp=8.0.1=hc9558a2_0
  - lz4-c=1.9.2=he1b5a44_1
  - lzstring=1.0.4=py_1001
  - mafft=7.471=h516909a_0
  - markdown=3.1.1=py37_0
  - markupsafe=1.1.1=py37h14c3975_1
  - matplotlib-base=3.2.2=py37h30547a4_0
  - mcl=14.137=pl526h516909a_5
  - megahit=1.2.9=h8b12597_0
  - minced=0.4.2=0
  - miniasm=0.3_r179=hed695b0_1
  - minimap2=2.17=hed695b0_2
  - mlst=2.19.0=0
  - multiqc=1.9=pyh9f0ad1d_0
  - ncurses=6.1=hf484d3e_1002
  - networkx=2.4=py_1
  - numpy=1.19.0=py37h8960a57_0
  - openjdk=11.0.1=hacce0ff_1020
  - openmp=8.0.1=0
  - openssl=1.1.1g=h7b6447c_0
  - paml=4.9=h516909a_5
  - pango=1.42.4=h7062337_4
  - parallel=20200522=0
  - pcre=8.44=he1b5a44_0
  - pcre2=10.35=h2f06484_0
  - perl=5.26.2=h516909a_1006
  - perl-aceperl=1.92=pl526_2
  - perl-algorithm-diff=1.1903=pl526_2
  - perl-algorithm-munkres=0.08=pl526_1
  - perl-apache-test=1.40=pl526_1
  - perl-app-cpanminus=1.7044=pl526_1
  - perl-appconfig=1.71=pl526_1
  - perl-archive-tar=2.32=pl526_0
  - perl-array-compare=3.0.1=pl526_1
  - perl-array-utils=0.5=pl526_2
  - perl-autoloader=5.74=pl526_2
  - perl-base=2.23=pl526_1
  - perl-bio-asn1-entrezgene=1.73=pl526_1
  - perl-bio-coordinate=1.007001=pl526_1
  - perl-bio-featureio=1.6.905=pl526_2
  - perl-bio-phylo=0.58=pl526_2
  - perl-bio-samtools=1.43=pl526h1341992_1
  - perl-bio-tools-phylo-paml=1.7.3=pl526_1
  - perl-bio-tools-run-alignment-clustalw=1.7.4=pl526_1
  - perl-bio-tools-run-alignment-tcoffee=1.7.4=pl526_2
  - perl-bioperl=1.7.2=pl526_11
  - perl-bioperl-core=1.007002=pl526_2
  - perl-bioperl-run=1.007002=pl526_4
  - perl-business-isbn=3.004=pl526_0
  - perl-business-isbn-data=20140910.003=pl526_0
  - perl-cache-cache=1.08=pl526_0
  - perl-capture-tiny=0.48=pl526_0
  - perl-carp=1.38=pl526_3
  - perl-cgi=4.44=pl526h14c3975_1
  - perl-class-data-inheritable=0.08=pl526_1
  - perl-class-inspector=1.34=pl526_0
  - perl-class-load=0.25=pl526_0
  - perl-class-load-xs=0.10=pl526h6bb024c_2
  - perl-class-method-modifiers=2.12=pl526_0
  - perl-clone=0.42=pl526h516909a_0
  - perl-common-sense=3.74=pl526_2
  - perl-compress-raw-bzip2=2.087=pl526he1b5a44_0
  - perl-compress-raw-zlib=2.087=pl526hc9558a2_0
  - perl-config-general=2.63=pl526_0
  - perl-constant=1.33=pl526_1
  - perl-convert-binary-c=0.78=pl526h6bb024c_3
  - perl-convert-binhex=1.125=pl526_1
  - perl-crypt-rc4=2.02=pl526_1
  - perl-data-dumper=2.173=pl526_0
  - perl-data-optlist=0.110=pl526_2
  - perl-data-stag=0.14=pl526_1
  - perl-date-format=2.30=pl526_2
  - perl-db-file=1.852=pl526h14c3975_0
  - perl-dbd-sqlite=1.64=pl526h516909a_0
  - perl-dbi=1.642=pl526_0
  - perl-devel-globaldestruction=0.14=pl526_0
  - perl-devel-overloadinfo=0.005=pl526_0
  - perl-devel-stacktrace=2.04=pl526_0
  - perl-digest-hmac=1.03=pl526_3
  - perl-digest-md5=2.55=pl526_0
  - perl-digest-md5-file=0.08=pl526_2
  - perl-digest-perl-md5=1.9=pl526_1
  - perl-digest-sha1=2.13=pl526h6bb024c_1
  - perl-dist-checkconflicts=0.11=pl526_2
  - perl-dynaloader=1.25=pl526_1
  - perl-email-date-format=1.005=pl526_2
  - perl-encode=2.88=pl526_1
  - perl-encode-locale=1.05=pl526_6
  - perl-error=0.17027=pl526_1
  - perl-eval-closure=0.14=pl526h6bb024c_4
  - perl-exception-class=1.44=pl526_0
  - perl-exporter=5.72=pl526_1
  - perl-exporter-tiny=1.002001=pl526_0
  - perl-extutils-makemaker=7.36=pl526_1
  - perl-file-find-rule=0.34=pl526_5
  - perl-file-grep=0.02=pl526_3
  - perl-file-listing=6.04=pl526_1
  - perl-file-path=2.16=pl526_0
  - perl-file-slurp-tiny=0.004=pl526_1
  - perl-file-slurper=0.012=pl526_0
  - perl-file-sort=1.01=pl526_2
  - perl-file-spec=3.48_01=pl526_1
  - perl-file-temp=0.2304=pl526_2
  - perl-file-which=1.23=pl526_0
  - perl-findbin=1.51=pl526_2
  - perl-font-afm=1.20=pl526_2
  - perl-font-ttf=1.06=pl526_0
  - perl-gd=2.71=pl526he860b03_0
  - perl-getopt-long=2.50=pl526_1
  - perl-graph=0.9704=pl526_1
  - perl-graph-readwrite=2.09=pl526_2
  - perl-graphviz=2.24=pl526h734ff71_0
  - perl-html-element-extended=1.18=pl526_1
  - perl-html-entities-numbered=0.04=pl526_1
  - perl-html-formatter=2.16=pl526_0
  - perl-html-parser=3.72=pl526h6bb024c_5
  - perl-html-tableextract=2.13=pl526_2
  - perl-html-tagset=3.20=pl526_3
  - perl-html-tidy=1.60=pl526_0
  - perl-html-tree=5.07=pl526_1
  - perl-html-treebuilder-xpath=0.14=pl526_1
  - perl-http-cookies=6.04=pl526_0
  - perl-http-daemon=6.01=pl526_1
  - perl-http-date=6.02=pl526_3
  - perl-http-message=6.18=pl526_0
  - perl-http-negotiate=6.01=pl526_3
  - perl-image-info=1.38=pl526_1
  - perl-image-size=3.300=pl526_2
  - perl-io-compress=2.087=pl526he1b5a44_0
  - perl-io-html=1.001=pl526_2
  - perl-io-sessiondata=1.03=pl526_1
  - perl-io-socket-ssl=2.066=pl526_0
  - perl-io-string=1.08=pl526_3
  - perl-io-stringy=2.111=pl526_1
  - perl-io-tty=1.12=pl526_1
  - perl-io-zlib=1.10=pl526_2
  - perl-ipc-run=20180523.0=pl526_0
  - perl-ipc-sharelite=0.17=pl526h6bb024c_1
  - perl-jcode=2.07=pl526_2
  - perl-json=4.02=pl526_0
  - perl-json-xs=2.34=pl526h6bb024c_3
  - perl-lib=0.63=pl526_1
  - perl-libwww-perl=6.39=pl526_0
  - perl-libxml-perl=0.08=pl526_2
  - perl-list-moreutils=0.428=pl526_1
  - perl-list-moreutils-xs=0.428=pl526_0
  - perl-log-log4perl=1.49=pl526_0
  - perl-lwp-mediatypes=6.04=pl526_0
  - perl-lwp-protocol-https=6.07=pl526_4
  - perl-lwp-simple=6.15=pl526h470a237_4
  - perl-mailtools=2.21=pl526_0
  - perl-math-bezier=0.01=pl526_1
  - perl-math-cdf=0.1=pl526h14c3975_5
  - perl-math-derivative=1.01=pl526_0
  - perl-math-random=0.72=pl526h14c3975_2
  - perl-math-round=0.07=pl526_1
  - perl-math-spline=0.02=pl526_2
  - perl-math-vecstat=0.08=pl526_1
  - perl-mime-base64=3.15=pl526_1
  - perl-mime-lite=3.030=pl526_1
  - perl-mime-tools=5.508=pl526_1
  - perl-mime-types=2.17=pl526_0
  - perl-mldbm=2.05=pl526_1
  - perl-module-implementation=0.09=pl526_2
  - perl-module-runtime=0.016=pl526_1
  - perl-module-runtime-conflicts=0.003=pl526_0
  - perl-moo=2.003004=pl526_0
  - perl-moose=2.2011=pl526hf484d3e_1
  - perl-mozilla-ca=20180117=pl526_1
  - perl-mro-compat=0.13=pl526_0
  - perl-net-http=6.19=pl526_0
  - perl-net-ssleay=1.88=pl526h90d6eec_0
  - perl-ntlm=1.09=pl526_4
  - perl-number-compare=0.03=pl526_2
  - perl-number-format=1.75=pl526_3
  - perl-ole-storage_lite=0.19=pl526_3
  - perl-package-deprecationmanager=0.17=pl526_0
  - perl-package-stash=0.38=pl526hf484d3e_1
  - perl-package-stash-xs=0.28=pl526hf484d3e_1
  - perl-params-util=1.07=pl526h6bb024c_4
  - perl-params-validate=1.29=pl526h14c3975_1
  - perl-parent=0.236=pl526_1
  - perl-parse-recdescent=1.967015=pl526_0
  - perl-parse-yapp=1.21=pl526_0
  - perl-path-tiny=0.108=pl526_0
  - perl-pathtools=3.75=pl526h14c3975_1
  - perl-pdf-api2=2.035=pl526_0
  - perl-perlio-utf8_strict=0.007=pl526h6bb024c_1
  - perl-pod-escapes=1.07=pl526_1
  - perl-pod-usage=1.69=pl526_1
  - perl-postscript=0.06=pl526_2
  - perl-readonly=2.05=pl526_0
  - perl-regexp-common=2017060201=pl526_0
  - perl-role-tiny=2.000008=pl526_0
  - perl-scalar-list-utils=1.52=pl526h516909a_0
  - perl-set-intspan=1.19=pl526_1
  - perl-set-scalar=1.29=pl526_2
  - perl-soap-lite=1.19=pl526_1
  - perl-socket=2.027=pl526_1
  - perl-sort-naturally=1.03=pl526_2
  - perl-spreadsheet-parseexcel=0.65=pl526_2
  - perl-spreadsheet-writeexcel=2.40=pl526_2
  - perl-statistics-basic=1.6611=pl526_2
  - perl-statistics-descriptive=3.0702=pl526_0
  - perl-storable=3.15=pl526h14c3975_0
  - perl-sub-exporter=0.987=pl526_2
  - perl-sub-exporter-progressive=0.001013=pl526_0
  - perl-sub-identify=0.14=pl526h14c3975_0
  - perl-sub-install=0.928=pl526_2
  - perl-sub-name=0.21=pl526_1
  - perl-sub-quote=2.006003=pl526_1
  - perl-sub-uplevel=0.2800=pl526h14c3975_2
  - perl-svg=2.84=pl526_0
  - perl-svg-graph=0.02=pl526_3
  - perl-task-weaken=1.06=pl526_0
  - perl-template-toolkit=2.26=pl526_1
  - perl-test=1.26=pl526_1
  - perl-test-deep=1.128=pl526_1
  - perl-test-differences=0.67=pl526_0
  - perl-test-exception=0.43=pl526_2
  - perl-test-harness=3.42=pl526_0
  - perl-test-leaktrace=0.16=pl526h14c3975_2
  - perl-test-most=0.35=pl526_0
  - perl-test-requiresinternet=0.05=pl526_0
  - perl-test-warn=0.36=pl526_1
  - perl-text-csv=2.00=pl526_0
  - perl-text-diff=1.45=pl526_0
  - perl-text-format=0.59=pl526_2
  - perl-text-glob=0.11=pl526_1
  - perl-tie-ixhash=1.23=pl526_2
  - perl-time-hires=1.9760=pl526h14c3975_1
  - perl-time-local=1.28=pl526_1
  - perl-time-piece=1.27=pl526_1
  - perl-timedate=2.30=pl526_1
  - perl-tree-dag_node=1.31=pl526_0
  - perl-try-tiny=0.30=pl526_1
  - perl-type-tiny=1.004004=pl526_0
  - perl-types-serialiser=1.0=pl526_2
  - perl-unicode-map=0.112=pl526h6bb024c_3
  - perl-uri=1.76=pl526_0
  - perl-www-robotrules=6.02=pl526_3
  - perl-xml-dom=1.46=pl526_0
  - perl-xml-dom-xpath=0.14=pl526_1
  - perl-xml-filter-buffertext=1.01=pl526_2
  - perl-xml-libxml=2.0132=pl526h7ec2d77_1
  - perl-xml-libxslt=1.94=pl526_1
  - perl-xml-namespacesupport=1.12=pl526_0
  - perl-xml-parser=2.44_01=pl526ha1d75be_1002
  - perl-xml-regexp=0.04=pl526_2
  - perl-xml-sax=1.02=pl526_0
  - perl-xml-sax-base=1.09=pl526_0
  - perl-xml-sax-expat=0.51=pl526_3
  - perl-xml-sax-writer=0.57=pl526_0
  - perl-xml-simple=2.25=pl526_1
  - perl-xml-twig=3.52=pl526_2
  - perl-xml-writer=0.625=pl526_2
  - perl-xml-xpath=1.44=pl526_0
  - perl-xml-xpathengine=0.14=pl526_2
  - perl-xsloader=0.24=pl526_0
  - perl-yaml=1.29=pl526_0
  - pigz=2.4=h84994c4_0
  - pilon=1.23=2
  - pip=20.1.1=py_1
  - pixman=0.38.0=h516909a_1003
  - popt=1.16=h299ea2f_2002
  - prank=v.170427=hc9558a2_3
  - prodigal=2.6.3=h516909a_2
  - prokka=1.14.6=pl526_0
  - pthread-stubs=0.4=h14c3975_1001
  - pycparser=2.20=py_2
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pysocks=1.7.1=py37_1
  - python=3.7.6=cpython_h8356626_6
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pyyaml=5.3.1=py37h7b6447c_1
  - quast=5.0.2=py37pl526hb5aa323_2
  - racon=1.4.13=he513fc3_0
  - readline=8.0=h46ee950_1
  - requests=2.24.0=py_0
  - roary=3.13.0=pl526h516909a_0
  - rsync=3.1.3=hed695b0_1002
  - samclip=0.4.0=0
  - samtools=1.10=h9402c20_2
  - seqtk=1.3=hed695b0_2
  - setuptools=49.2.0=py37hc8dfbb8_0
  - shovill=1.1.0=0
  - simplejson=3.17.2=py37h8f50634_0
  - six=1.15.0=pyh9f0ad1d_0
  - skesa=2.3.0=he1c1bb9_2
  - snippy=4.3.6=0
  - snp-sites=2.5.1=hed695b0_0
  - snpeff=4.5covid19=1
  - spades=3.14.0=h2d02072_0
  - spectra=0.0.11=py_1
  - sqlite=3.32.3=hcee41ef_1
  - t_coffee=11.0.8=py37hea885bf_8
  - tar=1.32=hd4ba37b_0
  - tbb=2020.1=hc9558a2_0
  - tbl2asn-forever=25.7.1f=0
  - tidyp=1.04=1
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.4=py37h8f50634_1
  - trimmomatic=0.39=1
  - unicycler=0.4.8=py37h8b12597_0
  - unzip=6.0=h516909a_1
  - urllib3=1.25.9=py_0
  - vcflib=1.0.0_rc3=py37hc088bd4_0
  - velvet=1.2.10=hed695b0_3
  - vt=2015.11.10=h5ef6573_4
  - wget=1.20.1=h22169c7_0
  - wheel=0.34.2=py_1
  - xorg-fixesproto=5.0=h14c3975_1002
  - xorg-inputproto=2.3.2=h14c3975_1002
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxpm=3.5.13=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-libxt=1.1.5=h516909a_1003
  - xorg-libxtst=1.2.3=h516909a_1002
  - xorg-recordproto=1.14.2=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.5=h516909a_1
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h6597ccf_3
prefix: /home/ubuntu/miniconda3/envs/nullarbor

